### ISSUE TITLE
Add Expert Settings

### ISSUE THREAD

**Issue by williandalton** [hacki11/ioBroker.valloxmv#11]
Die "Speziellen Einstellungen" aus der WebGUI sollten unterstützt werden
Aktuell fehlen noch:
- Außentemperatur-Sensorsteuerung
- Methoden der Temperaturregelung
- Feuchtigkeit

**Comment by williandalton** [comment]
Ich habe die Sensor-Einstellungen "Methoden der Temperaturregelung" (A_CYC_SUPPLY_HEATING_ADJUST_MODE) und der "Feuchtigkeit" (A_CYC_RH_LEVEL_MODE) hinzugefügt. 

Die Außentemperatur-Sensorsteuerung (A_CYC_OPT_TEMP_SENSOR_MODE) bräuchte noch ein Review, hier gibt es noch Probleme mit der aktuellem Einstellungen / der Einheit?

**Comment by hliebscher** [comment]
Funktioniert schon mal gut

für den Sensor Mode  (A_CYC_OPT_TEMP_SENSOR_MODE)sollten die Werte 

"Opt. Sensor mode" [None, MLV, Airheater] sein also keine Einheit

**Comment by williandalton** [comment]
Bereinigte Lösung unter neuem Pull Request bereitgestellt (hoffe das ist ok so von der Vorgehensweise)
https://github.com/hacki11/ioBroker.valloxmv/pull/13

Setzt folgenden Fix voraus:
https://github.com/danielbayerlein/vallox-api/pull/5

**Comment by danielbayerlein** [comment]
@williandalton FYI: Version 0.1.2 is now available.

**Comment by hliebscher** [comment]
Klappt perfekt DANKE für den guten Job

können wir noch die %RH-Grenze aus den speziellen Einstellungen als Wert hinzufügen.
Damit wir die Lüfterdrehzahl gesteuert wenn der Haken in den Profilen gesetzt ist.

**Comment by hacki11** [comment]
Danke für die rege Beteiligung, bei Gelegenheit könntet ihr mich mal in eure Steuerungen einweihen. 
Meine Anlage ist noch nicht mal eingepegelt, es läuft nur das Web interface :D

**Comment by hacki11** [comment]
Ich zieh morgen die neue Version von vallox-api rein.

**Comment by hliebscher** [comment]
Können wir gerne machen habe die Vallox perfekt eingerichtet ;-)

**Comment by williandalton** [comment]
Die Portierung meiner Steuerung nach JS steht immer noch aus, aber ich kann ja mal die "alten" Strategien aus meiner C# Implementierung und meine Erfahrung damit beisteuern...
Wie schon erwähnt ging es mir hauptsächlich drum, die Luftfeuchtigkeit im Winter zu erhalten, da man sich diese sonst durch konstantes Lüften "rauspustet" und das auf Dauer nicht besonders angenehm/gesund ist.

Außerdem wollte ich mangels Oberfläche für die Automatisierung die WebGUI der Vallox weiter nutzen und wollte die Profile nicht beeinflussen. Daher steuere ich nur über Anlage ein/aus.
Um den WAF zu erhöhen, übersteuert das manuelle Bedienen der Vallox WebGUI eine mögliche Automatisierung für x Stunden. Wenn man also per GUI Stoßlüften oder "Anlage ein" geschaltet hat, dann bleibt der Zustand dann auch erst mal so.

In meiner Ersten Steuerung hatte ich noch keinen Sensor für die Luftfeuchtigkeit innen. Daher habe ich mich zunächst an der Außentemperatur zur Steuerung orientiert. In dieser Variante hatte ich auch noch den Ansatz Sommer- und Wintersteuerung in einer Automatisierunglogik zu kombinieren.
Daher gibt es in der Variante auch noch die maximale Außentemperatur, damit es im Sommer nicht zu warm drinnen wird.
Im Code sieht das dann so aus, ich hoffe es ist auch ohne weitere Klassen verständlich:
`        new void initVentiControlAutomationParameter()
        {
   
            double d;
            string h;

            ventiControlAutomationParameter = new VentiControlAutomationParameter();
            h = System.Configuration.ConfigurationManager.AppSettings["minWorkingTemp"];
            if (double.TryParse(h, out d))
            {
                ventiControlAutomationParameter.MinWorkingTemp = d;
            }
            else
            {
                ventiControlAutomationParameter.MinWorkingTemp = -2;
            }

            h = System.Configuration.ConfigurationManager.AppSettings["maxWorkingTemp"];
            if (double.TryParse(h, out d))
            {
                ventiControlAutomationParameter.MaxWorkingTemp = d;
            }
            else
            {
                ventiControlAutomationParameter.MaxWorkingTemp = 23;
            }


        }

        public override void EvaluateVentiState(Object state)
        {
            log.Debug("Evaluation Venti State");

            try
            {
                if (base.sensorDataManagerOpenWeather.IsReady() == false || base.AutomationPossible() == false)
                {
                    return;
                }

         

                if (ventiControlAutomationParameter == null)
                {
                    log.Warn("No Control Parameter definded");
                    return;
                }

                PowerState newPowerState = PowerState.Undefined;
             


                if (sensorDataManagerOpenWeather.SensorDataCurrent.Temperature < ventiControlAutomationParameter.MinWorkingTemp)
                {
                    if (ventiMonitor.DataModel.PowerState == PowerState.On)
                    {
                        log.InfoFormat("AutomationEvent: Pretty Cold, TempOutside < MinWorkingTemp, {0} < {1}, shutting down...", sensorDataManagerOpenWeather.SensorDataCurrent.Temperature, ventiControlAutomationParameter.MinWorkingTemp);

                        newPowerState = PowerState.Off;
                    }
                }


                if (sensorDataManagerOpenWeather.SensorDataCurrent.Temperature > ventiControlAutomationParameter.MaxWorkingTemp)
                {
                    if (ventiMonitor.DataModel.PowerState == PowerState.On)
                    {
                        log.InfoFormat("AutomationEvent: Pretty Hot, TempOutside > MaxWorkingTemp, {0} > {1}, shutting down...", sensorDataManagerOpenWeather.SensorDataCurrent.Temperature, ventiControlAutomationParameter.MaxWorkingTemp);
                        newPowerState = PowerState.Off;
                    }
                }


                if (newPowerState == PowerState.Undefined)
                {
                    if (sensorDataManagerOpenWeather.SensorDataCurrent.Temperature > ventiControlAutomationParameter.MinWorkingTemp &&
                        sensorDataManagerOpenWeather.SensorDataCurrent.Temperature < ventiControlAutomationParameter.MaxWorkingTemp)
                        if (ventiMonitor.DataModel.PowerState == PowerState.Off)
                        {
                            log.InfoFormat("AutomationEvent: Moderate Temp, TempOutside between MinWorkingTemp and MaxWorkingTemp, {0} > {1} > {2}, starting up...", ventiControlAutomationParameter.MinWorkingTemp, sensorDataManagerOpenWeather.SensorDataCurrent.Temperature, ventiControlAutomationParameter.MaxWorkingTemp);
                            newPowerState = PowerState.On;
                        }
                }

                if (newPowerState == PowerState.Undefined)
                {
                    log.Info("No Change needed, everything ok");
                }
                else
                {
                    log.InfoFormat("New PowerState determinated: {0}", newPowerState.ToString());
                    if (controlEnabled)
                    {
                        ventiMonitor.ExpectChange = true;
                        lastControlTime = DateTime.Now;
                        ventiController.SetPowerState(newPowerState);
                    }
                    else
                    {
                        log.InfoFormat("Sending new PowerState {0} skipped, because Control is disabled", newPowerState.ToString());
                    }
                }
            }
            catch (Exception ex)
            {
                log.Error("Exeption in EvaluateVentiState", ex);

            }

        }
`

In der Praxis war das schon besser als nix, führte aber dazu dass teilweise doch noch zu lange gelüftet wurde und die Luftfeuchte trotzdem zu stark sank. Im Sommer funktionierte die "Tagabschaltung" bei zu hohen Temperaturen ganz gut, allerdings wurde zu spät wieder die Lüftung aktiviert, obwohl es draußen schon kälter war als drinnen. Hier waren auch wieder zu wenig Sensoren vorhanden.

Anfang des letzten Winters habe ich dann neue Sensoren für innen eingebunden und die Steuerung überarbeitet. Nach dem neuen Konzept habe ich Lüftungsintervalle nebst minimaler Luftfeuchte und maximale Luftfeuchteabfall definiert. Diese Art der Steuerung erlaubt es bei zu starkem Lüften, dass sich die Luftfeuchte erst gar nicht zu extrem fällt und trotzdem einigermaßen gut gelüftet wird. Ich fahre zwei Intervalle, einst morgens zwischen 07:30 und 11:00 und ein zweites am Nachmittag von 16:00-18:00
Mit der Einstellung sind wir ganz zufrieden. Nichts desto trotz läuft hier im Winter regelmäßig der Luftwäscher.

Hier noch der Code
` new void initVentiControlAutomationParameter()
        {
// Nur Dummy, Intervalle kommen sonst aus der Config
            ventingIntervals = new List<VentingInterval>();
            ventingIntervals.Add(new VentingInterval() { Id = 1, IntervalStart = new DateTime(1, 1, 1, 7, 30, 0), IntervalEnd = new DateTime(1, 1, 1, 10, 30, 0), MinHumidity = 40, MaxHumidityDrop = 15 });
            ventingIntervals.Add(new VentingInterval() { Id = 2, IntervalStart = new DateTime(1, 1, 1, 15, 30, 0), IntervalEnd = new DateTime(1, 1, 1, 17, 30, 0), MinHumidity = 40, MaxHumidityDrop = 10 });
            ventingIntervals.Add(new VentingInterval() { Id = 3, IntervalStart = new DateTime(1, 1, 1, 20, 30, 0), IntervalEnd = new DateTime(1, 1, 1, 21, 22, 0), MinHumidity = 40, MaxHumidityDrop = 3 });

        }

        public override void EvaluateVentiState(Object state)
        {
            log.Debug("Evaluation Venti State");

            try
            {
                if (!base.sensorDataManagerESPTempHygro1.IsReady())
                {
                    log.Debug("sensorDataManagerESPTempHygro1 is not ready");
                    return;
                }

                if (!base.AutomationPossible())
                {
                    log.Debug("AutomationPossible is false");
                    return;
                }



                if (ventingIntervals == null || ventingIntervals.Count == 0)
                {
                    log.Warn("No ventingIntervals definded");
                    return;
                }

      
                PowerState newPowerState = PowerState.Undefined;

                // Current ungültig machen wenn nötig
                if (currentVentingInterval != null)
                {
                    if (!IsVentingIntervallStillValid(currentVentingInterval))
                    {
                        log.InfoFormat("Venting Intervall is not valid anymore, EndTime: ", currentVentingInterval.IntervalEnd.TimeOfDay.ToString() ) ;

                        // Default PowerState, wenn ein Intervall endet ist Off
                        newPowerState = PowerState.Off;
                        currentVentingInterval = null;
                    }
                }

                if (currentVentingInterval == null)
                {                    
                    currentVentingInterval = GetCurrentVentingInterval();
                    if (currentVentingInterval != null)
                    {
                        // Hier wird ein VentingIntervall zum ersten mal in diesem Intervall aktiv
                        log.InfoFormat("Venting Intervall begins, StartTime: ", currentVentingInterval.IntervalStart.TimeOfDay.ToString());
                        currentVentingInterval.Aborted = false;
                        currentVentingInterval.IntervalStart = DateTime.Now;
                        currentVentingInterval.HumidityOnStart = sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity;
                    }
                }

                if (currentVentingInterval != null)
                {
                    if (currentVentingInterval.Aborted)
                    {
                        // Wenn das aktuelle Intervall bereits abgebrochen wurde, muss nix mehr gemacht werden
                        log.Debug("Intervall already Abortet in prio Check, nothing to do");
                    }
                    else
                    {
                        if (sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity < currentVentingInterval.MinHumidity)
                        {
                            log.InfoFormat("MinHumidity of Interval reached, CurrentHum < MinHumidity, {0} < {1}, shutting down...", sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity, currentVentingInterval.MinHumidity);
                            currentVentingInterval.Aborted = true;
                            newPowerState = PowerState.Off;
                            
                        }


                        if (currentVentingInterval.HumidityOnStart - sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity > currentVentingInterval.MaxHumidityDrop )
                        {
                            log.InfoFormat("MaxHumidityDrop of Interval reached, HumidityOnStart - CurrentHum > MaxHumidityDrop, {0} - {1} > {2} , shutting down...", currentVentingInterval.HumidityOnStart , sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity , currentVentingInterval.MaxHumidityDrop);
                            currentVentingInterval.Aborted = true;
                            newPowerState = PowerState.Off;
                        }

                        // Wenn bis hierher keine Regel die Ausführung abgebroche hat, sollte die Anlage an sein
                        if (!currentVentingInterval.Aborted)
                        {
                            log.InfoFormat("No Rule hit till now, Venting should be ok. CurrentHum: {0}, MinHumidity: {1}, MaxDrop: {2}, CurrentDrop: {3}", sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity, currentVentingInterval.MinHumidity, currentVentingInterval.MaxHumidityDrop , currentVentingInterval.HumidityOnStart - sensorDataManagerESPTempHygro1.SensorDataCurrent.Humidity);
                            newPowerState = PowerState.On;
                        }

                    }
                }

                if (newPowerState == PowerState.Undefined)
                {
                    // Wenn bis hier keine Regel gegriffen hat, befinden wir uns zwischen zwei Intervallen
                    newPowerState = PowerState.Off;
                    log.InfoFormat("No Rule hit, PowerState.Off should be right");
                }

                if (newPowerState == ventiMonitor.DataModel.PowerState)
                {
                    log.InfoFormat("No Change needed, Device is already in PowerState {0}", ventiMonitor.DataModel.PowerState);
                }
                else
                {
                    log.InfoFormat("New PowerState determinated: {0}", newPowerState.ToString());
                    if (controlEnabled)
                    {
                        ventiMonitor.ExpectChange = true;
                        lastControlTime = DateTime.Now;
                        ventiController.SetPowerState(newPowerState);
                    }
                    else
                    {
                        log.InfoFormat("Sending new PowerState {0} skipped, because Control is disabled", newPowerState.ToString());
                    }
                }
            }
            catch (Exception ex)
            {
                log.Error("Exeption in EvaluateVentiState", ex);

            }

        }`

Für den Sommer brauche ich jetzt noch eine neue Logik, in der Tagsüber die Anlage aus geht und Nachts (gerne auch etwas kräftiger) gekühlt wird. Das wird dann sicher das erste Automatisierungsskript unterm ioBroker :-)

Hoffe ihr könnte mir den Ansätzen etwas anfangen und es ist etwas für eure Logiken dabei.

**Comment by hacki11** [comment]
Wow, danke für die ausführlichen Infos!
Hat deine Vallox ein Modul zur Feuchterückgewinnung? Ich hab das drin und bin schon gespannt wie gut das in der Realität funktioniert. Vermutlich wird es aber trotzdem notwendig sein solche Intervalle zu fahren.

**Comment by williandalton** [comment]
Gerne ;-)
Feuchterückgewinnung hat meine Vallox 350MV noch nicht, aber man kann den Wärmetauscher durch nen Enthalpietauscher ersetzen. Der ist aber auch nicht ganz günstig, daher wurde die Anschaffung erst mal aufgeschoben. 
Wenn Du sowas schon drin hast ist das ja super, denke dann kannst Du entweder länger lüften oder musst weniger "nachbefeuchten"

**Comment by hacki11** [comment]
kann ich das schließen oder ist noch was offen?

**Comment by radierer** [comment]
Bevor hier geschlossen wird, nochmal ein kleine Frage von mir, für die ich nicht extra ein neues Issue eröffnen wollte.
Ist es aktuell noch nicht vorgesehen, die Ventilatorleistung in den einzelnen Profilen zu ändern? Denn das funktioniert bei mir irgendwie nicht. In ioBroker habe ich unter Objekte bei den jeweiligen States keine Möglichkeit, die Ventilatorleistung (0-100) zu überschreiben. Per Skript funktioniert das und auch in den unter Objekte wird beim state kurz der im Skript hinterlegte Wert angezeigt. Der Wert kommt aber nie bei der Anlage an und wird beim nächsten Polling wieder mit dem vorherigen Wert überschrieben.
Ich hoffe ihr könnt nachvollziehen, was ich meine .. :)

**Comment by hliebscher** [comment]
Das funktioniert perfekt. Habe ich gerade getestet.Der Wert muss unter vallox -> profiles -> home ->

valloxmv.0.profiles.home.A_CYC_HOME_SPEED_SETTING

geändert werden. Wird dann auch im WebFront direkt angezeigt.

**Comment by hacki11** [comment]
Kann es auch ändern und es kommt im Frontend an.
Was mich jedoch stört ist, dass ein leeres Drop Down Feld angezeigt wird und man etwas umständlich zum Popup gelangt:
![image](https://user-images.githubusercontent.com/15319906/57807918-8b5ae100-7762-11e9-9fd6-c292943c1ec0.png)
Liegt das evtl. am Typ State und dem leeren "states" Objekt?

**Comment by hliebscher** [comment]
Stimmt ... ist blöd wenn man bestätigt steht auch gleich 0 drin

**Comment by radierer** [comment]
Hm ok .. ich werds heute Abend nochmal probieren. Unter den Profilen hab ich es geändert. Allerdings hab ich zum testen immer das "away" Profil geändert. Aber daran sollte es ja auch nicht liegen denke ich?!
Meine Anlage ist eine VP 270 MV. Ich gebe dann heute Abend nochmal Rückmeldung.

**Comment by radierer** [comment]
So, hier meine versprochene Rückmeldung. Funktioniert bei mir nun auch problemlos. Mein Fehler war wohl, dass ich in meinem Blockly-Skript erst immer "akualisiere Objekt-ID" genommen hatte. Habs dann mal mit "steuere Objekt-ID" probiert, was sofort funktionierte.

**Comment by hacki11** [comment]
Hab das Drop-Down gefixt, die Booleans haben nun eine checkbox und haben die Role "switch" statt "state"
![image](https://user-images.githubusercontent.com/15319906/57980294-ebcf7400-7a29-11e9-9a39-d40faf771f45.png)
![image](https://user-images.githubusercontent.com/15319906/57980297-f853cc80-7a29-11e9-82f7-6b935a7a44d8.png)

**Comment by hliebscher** [comment]
Klappt nicht habe das gerade installiert
gibt auch keine Drop Down mehr ?

**Comment by hliebscher** [comment]
Klappt jetzt Klasse Danke 
kann jetzt glaube ich geschlossen werden 

Tolle Arbeit!

**Comment by hacki11** [comment]
Damit wir es in das Repo schaffen bräuchte ich euer Feedback in folgendem Thread:
https://forum.iobroker.net/topic/21897/aufruf-valloxmv-adapter

Das ist Voraussetzung für die Aufnahme.

**Comment by hliebscher** [comment]
Kannst Du bitte den Link mit vorn in die Beschreibung bringen? 
mit freundlichen Grüßen
