### ISSUE TITLE
Fehler nach Installation, Instanz bleibt offline

### ISSUE THREAD

**Issue by jayfizzle** [hacki11/ioBroker.valloxmv#17]
Hallo zusammen,

Habe heute mal den Adapter für die Vallox Lüftungsanlage installiert, IP eingetragen gespeichert und gestartet! 

Erhalte folgenden Fehler(Instanz bleibt rot):

Caught	2019-05-22 13:49:59.377	error	by controller[0]: /opt/iobroker/node_modules/iobroker.valloxmv/main.js:17
host.raspberrypi	2019-05-22 13:49:58.979	info	instance system.adapter.valloxmv.0 started with pid 28520
host.raspberrypi	2019-05-22 13:49:28.949	info	Restart adapter system.adapter.valloxmv.0 because enabled
host.raspberrypi	2019-05-22 13:49:28.949	error	instance system.adapter.valloxmv.0 terminated with code 1 ()
Caught	2019-05-22 13:49:28.949	error	by controller[0]: at startup (bootstrap_node.js:153:9)
Caught	2019-05-22 13:49:28.949	error	by controller[0]: at run (bootstrap_node.js:387:7)
Caught	2019-05-22 13:49:28.949	error	by controller[0]: at Module.runMain (module.js:611:10)
Caught	2019-05-22 13:49:28.948	error	by controller[0]: at Function.Module._load (module.js:445:3)
Caught	2019-05-22 13:49:28.948	error	by controller[0]: at tryModuleLoad (module.js:453:12)
Caught	2019-05-22 13:49:28.948	error	by controller[0]: at Module.load (module.js:494:32)
Caught	2019-05-22 13:49:28.944	error	by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught	2019-05-22 13:49:28.944	error	by controller[0]: at Module._compile (module.js:549:28)
Caught	2019-05-22 13:49:28.944	error	by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught	2019-05-22 13:49:28.944	error	by controller[0]: at createScript (vm.js:56:10)
Caught	2019-05-22 13:49:28.944	error	by controller[0]: SyntaxError: Unexpected token ...
Caught	2019-05-22 13:49:28.944	error	by controller[0]: ^^^
Caught	2019-05-22 13:49:28.943	error	by controller[0]: ...options,
Caught	2019-05-22 13:49:28.942	error	by controller[0]: /opt/iobroker/node_modules/iobroker.valloxmv/main.js:17
host.raspberrypi	2019-05-22 13:49:28.547	info	instance system.adapter.valloxmv.0 started with pid 28512
host.raspberrypi	2019-05-22 13:48:58.519	info	Restart adapter system.adapter.valloxmv.0 because enabled
host.raspberrypi	2019-05-22 13:48:58.519

Was habe ich falsch gemacht?
Lüftungsanlage: ValloPlus 350 MV

Gruß
J

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hacki11** [comment]
Sieht aus als müsstest du Node aktualisieren. Welche Version von Node und NPM hast du drauf?

**Comment by jayfizzle** [comment]
Ups, 

Node: v6.14.1
npm: 3.10.10

Hmmm läuft derweil stabil, bedenken upzudaten :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hacki11** [comment]
Node 6 ist inzwischen EOL. Die aktuellen Adapter benötigen mindestens Node 8.
Deshalb bekommst du einen Syntax Error

**Comment by jayfizzle** [comment]
Werde ich mal ausprobieren bei Gelegenheit (habe noch keine genaue Idee wie ich genau updaten kann bzw soll).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jayfizzle** [comment]
Funktioniert nun nach dem Update, danke 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hacki11** [comment]
Optimal, kannst gern in https://forum.iobroker.net/topic/21897/aufruf-valloxmv-adapter/ Feedback geben damit wir das Teil Stelle bekommen
