### ISSUE TITLE
Lose object configurations after restart of this instance

### ISSUE THREAD

**Issue by rabru** [hacki11/ioBroker.valloxmv#20]
**Describe the bug**  
If I restart this instance, I will lose all settings of the related objects.

1.	Change the configuration of an object. Like collection the stats of the FanSpeed.
2.	Restart the instance
3.	You will recognize that the collection of the stats is stopped and the setup of the object is gone.

**To Reproduce**  
1.	Change the configuration of an object. Like collecting stats of the FanSpeed.
2.	Restart the instance
3.	You will recognize that the collection of the stats is stopped and the setup of the object is gone.

**Expected behavior**  
Keep the object configuration.

**Versions:**  
 - Adapter version: v1.0.0
 - JS-Controller version: v2.1.1
 - Node version: v8.11.3
 - Operating system: raspbian

**Additional context**  
I assume after a restart of the instance, all objects will be initiated new and therefore the original setup is overwritten. Could you please change this and keep the manual settings? Otherwise it is not possible to collect stats.

Thanks

**Comment by hacki11** [comment]
setObjectAsync is used instead of setObjectNotExistsAsync

**Comment by hacki11** [comment]
could you install the plugin from master and verify if the behavior is now as expected?
i will publish a release if you can confirm.

**Comment by rabru** [comment]
v1.0.1 works fine for me.
Thanks for the quick fix.
