### ISSUE TITLE
set active profile not working

### ISSUE THREAD

**Issue by xdaamg** [hacki11/ioBroker.valloxmv#22]
Does this adapter support to set 'active profile' already?

When i change object 'valloxmv.0.ACTIVE_PROFILE' from '1' (HOME) to '2' (AWAY) this change is not accepted by device Vallox 350 MV. No error/warning in logfile. Device profile remains '1'. After some time object value is also '1' again. Reading of all values without issue. 

Adapter Version 1.0.1
Node.js v10.18.1

**Comment by hacki11** [comment]
yes, i am using the profile switch every here and then since half a year.

can you verify if your object settings are the same as:

```
"type": "state",
  "common": {
    "name": "Ventilation profiles",
    "type": "number",
    "role": "indicator",
    "read": true,
    "write": true,
    "states": {
      "1": "HOME",
      "2": "AWAY",
      "3": "BOOST",
      "4": "FIREPLACE",
      "5": "EXTRA"
    },
    "min": 1,
    "max": 5
  }, ...
```
please set the logging of the valloxmv instance to silly, change the value and provide the logs.

**Comment by xdaamg** [comment]
Object settings are the same (just in different order).
I changed object id 'ACTIVE PROFILE' to '2' (without ACK):

`

valloxmv.0 | 2020-01-18 19:50:01.585 | debug | (13863) system.adapter.admin.0: logging true
-- | -- | -- | --
valloxmv.0 | 2020-01-18 19:50:01.584 | silly | (13863) States redis pmessage *.logging/system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1579373401571,"q":0,"from":"system.adapter.admin.0","lc":1579373401571}
valloxmv.0 | 2020-01-18 19:49:54.800 | debug | (13863) system.adapter.admin.0: logging false
valloxmv.0 | 2020-01-18 19:49:54.799 | silly | (13863) States redis pmessage *.logging/system.adapter.admin.0.logging:{"val":false,"ack":true,"ts":1579373394755,"q":0,"from":"system.adapter.admin.0","lc":1579373394755}
valloxmv.0 | 2020-01-18 19:48:43.947 | debug | (13863) system.adapter.admin.0: logging true
valloxmv.0 | 2020-01-18 19:48:43.946 | silly | (13863) States redis pmessage *.logging/system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1579373323932,"q":0,"from":"system.adapter.admin.0","lc":1579373323932}
valloxmv.0 | 2020-01-18 19:48:34.456 | debug | (13863) system.adapter.admin.0: logging false
valloxmv.0 | 2020-01-18 19:48:34.454 | silly | (13863) States redis pmessage *.logging/system.adapter.admin.0.logging:{"val":false,"ack":true,"ts":1579373314440,"q":0,"from":"system.adapter.admin.0","lc":1579373314440}
valloxmv.0 | 2020-01-18 19:48:12.491 | info | (13863) Connection established successfully
valloxmv.0 | 2020-01-18 19:48:12.351 | silly | (13863) States redis pmessage system.adapter.valloxmv.0.logLevel/system.adapter.valloxmv.0.logLevel:{"val":"silly","ack":true,"ts":1579373292338,"q":0,"from":"system.adapter.valloxmv.0","lc":15793732
valloxmv.0 | 2020-01-18 19:48:12.331 | info | (13863) Establish connection to ValloxMV (192.168.2.222:80)
valloxmv.0 | 2020-01-18 19:48:12.250 | info | (13863) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.valloxmv, node: v10.18.1

`

**Comment by hacki11** [comment]
In your log won't show any state change. if i set my instance to silly and change to "home" it looks like:

2020-01-18 20:40:27.871 - debug: valloxmv.0 state valloxmv.0.info.connection changed: true (ack = false)
--
2020-01-18 20:40:34.110 - silly: valloxmv.0 inMem message valloxmv.0.* valloxmv.0.ACTIVE_PROFILE val=1, ack=false, ts=1579376434107, q=0, from=system.adapter.admin.0, user=system.user.admin, lc=1579376434107
2020-01-18 20:40:34.111 - debug: valloxmv.0 state valloxmv.0.ACTIVE_PROFILE changed: 1 (ack = false)

**Comment by xdaamg** [comment]
I set 'valloxmv.0.ACTIVE_PROFILE' from '1' to '2' directly in 'iobroker objects' (without ACK).
Object is some seconds on '2' (red color) and after some time it's '1' again (green color). Vallox 350 MV profile is all the time on '1'.

I installed this adapter from iobroker repository. It's the same version as on your github account? https://github.com/hacki11/ioBroker.valloxmv/ 

Did not find any configuration settings in vallox device which i could change.

Any ideas? Permission problem?

**Comment by SpookyFishes** [comment]
I have the same problems. I used adapter 1.0.0 about 2 month without problem. Today I installed socket.io 2.1.2 as well. js-controller is version 2.1.1

Perhaps I can restore a backup with vallox Adapter 1.0.0 and have a look if it is working.

**Comment by SpookyFishes** [comment]
I just restored my backup of iobroker with vallox Adapter 1.0.0 and without socket.io
With this backup I can switch between valloxmv.0.ACTIVE_PROFILE (1) and (2) without any problems.

Then I updated to 1.0.1 successfully and tried to switch again the valloxmv.0.ACTIVE_PROFILE from (1) to (2) and the other way round. I tried it over my VIS and directly writing the value in the object. This time it wasn't successfull.

This is my logfile during the hole test:
```
valloxmv.0 | 2020-01-19 23:08:28.627 | info | (1234) Connection established successfully
-- | -- | -- | --
valloxmv.0 | 2020-01-19 23:08:28.423 | info | (1234) Establish connection to ValloxMV (192.168.178.22:80)
valloxmv.0 | 2020-01-19 23:08:28.385 | info | (1234) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.valloxmv, node: v10.18.1
valloxmv.0 | 2020-01-19 23:08:24.153 | info | (793) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
valloxmv.0 | 2020-01-19 23:08:24.152 | info | (793) terminating
valloxmv.0 | 2020-01-19 23:08:24.149 | info | (793) cleaned everything up...
valloxmv.0 | 2020-01-19 23:08:24.146 | info | (793) Got terminate signal TERMINATE_YOURSELF
valloxmv.0 | 2020-01-19 23:00:22.637 | info | (793) Connection established successfully
valloxmv.0 | 2020-01-19 23:00:21.541 | info | (793) Establish connection to ValloxMV (192.168.178.22:80)
valloxmv.0 | 2020-01-19 23:00:21.504 | info | (793) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.valloxmv, node: v10.18.1
```

**Comment by xdaamg** [comment]
I just unintalled 1.0.1 and installed 1.0.0, without any other change. I can confirm, profile change is working with 1.0.0.
With latest version 1.0.1 i can not change active profile.

**Comment by hacki11** [comment]
Good point, i will get into this tonight

**Comment by hacki11** [comment]
I think i fixed the issue, can you install from github master 1.0.2, give it a try and report back?

**Comment by SpookyFishes** [comment]
Thanks @hacki11 for the quick bugfix. I installed 1.0.2 and everything is fine. I can change the profile state over VIS and by changing the profile object directly. What I could see is that the other objects have the same values as shown on the "MyVallox Home" Homepage. So from my side everything looks great :1st_place_medal:

**Comment by xdaamg** [comment]
I successfully tested change of active profile in version 1.0.2 too. Thanks for solving it.

**Comment by hacki11** [comment]
Release waiting for merge
https://github.com/ioBroker/ioBroker.repositories/pull/586

**Comment by hacki11** [comment]
1.0.3 available now
