### ISSUE TITLE
 getaddrinfo ENOTFOUND http http:80 

### ISSUE THREAD

**Issue by derRobert85** [hacki11/ioBroker.valloxmv#30]
**Describe the bug**  
there is no connection to my ValloPlus 510 MV
 

**To Reproduce**  

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
in LOG i can see 

valloxmv.0 | 2020-08-19 22:19:47.825 | error | (5562) getaddrinfo ENOTFOUND http http:80
valloxmv.0 | 2020-08-19 22:19:47.820 | error | (5562) Connection failed
valloxmv.0 | 2020-08-19 22:19:47.819 | error | (5562) getaddrinfo ENOTFOUND http http:80
valloxmv.0 | 2020-08-19 22:19:47.576 | info | (5562) Establish connection to ValloxMV (http://192.168.13.100:80)
valloxmv.0 | 2020-08-19 22:19:47.530 | info | (5562) starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.valloxmv, node: v10.22.0, js-controller: 3.1.6
valloxmv.0 | 2020-08-19 22:19:42.031 | info | (4989) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
valloxmv.0 | 2020-08-19 22:19:42.029 | info | (4989) terminating
valloxmv.0 | 2020-08-19 22:19:42.028 | info | (4989) cleaned everything up...
valloxmv.0 | 2020-08-19 22:19:42.025 | info | (4989) Got terminate signal TERMINATE_YOURSELF

**Versions:**  
 - Adapter version: <1.1.1>
 - JS-Controller version: <3.1.6> 
 - Node version: <10.22.0> 
 - Operating system: <Raspian Buster>

**Additional context**

**Comment by hacki11** [comment]
Please remove the "http://" from the Adapter settings host

**Comment by hacki11** [comment]
closed due missing feedback
