### ISSUE TITLE
Type von Datenpunkt A_CYC_TEMP_OUTDOOR_AIR string statt number

### ISSUE THREAD

**Issue by Feuer-sturm** [hacki11/ioBroker.valloxmv#32]
Mindestens beim Datenpunkt valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR stimmt der type "number" von diesem Datenpunkt nicht mit dem intern verwendeten type überein.
Bitte auch für die anderen Datenpunkte prüfen.

Aufgefallen ist es bei mir, als ich die Außentemperatur in einen neuen Datenpunkt vom type "number" schreiben wollte

```
createState('0_userdata.0.lueftung.AussentemperaturBerechnet', 0, {name: 'Aussentemperatur berechnet so dass Schwankungen wie bei Defrost abgefangen werden', unit: '', type: 'number', role: 'value', def: 0});

var DP_Lueftung_AussentemperaturBerechnet = '0_userdata.0.lueftung.AussentemperaturBerechnet';
var DP_Lueftung_TempOutdoorAir = 'valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR';
...
temp = getState(DP_Lueftung_TempOutdoorAir).val;
setState(DP_Lueftung_AussentemperaturBerechnet,temp);
```
daraufhin kam folgende Warnung:

` javascript.0: You are assigning a string to the state "0_userdata.0.lueftung.AussentemperaturBerechnet" which expects a number. Please fix your code to use a number or change the state type to string. This warning might become an error in future versions. `

ValloxMV Version:  1.1.1
js-controller: 3.2.16
node: 12.18.3
nodejs: v12.18.3
npm: 6.14.6 
Admin: 4.2.1 
Java Script Engine: 4.10.15

`console.log(typeof getState(valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR).val);
` ergibt "string"

Die Eigenschaften vom Datenpunkt sehen aber wie folgt aus:
![image](https://user-images.githubusercontent.com/25422320/107887848-3f296b80-6f09-11eb-961d-aa92bef0457d.png)

Raw von valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR

```
{
  "type": "state",
  "common": {
    "name": "Outdoor air °C",
    "type": "number",
    "role": "value.temperature",
    "read": true,
    "write": false,
    "states": null,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": 0,
        "changesRelogInterval": "1800",
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "from": "system.adapter.valloxmv.0",
  "user": "system.user.admin",
  "ts": 1578944936139,
  "_id": "valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by hacki11** [comment]
Hab soeben einen Fix auf Github-Master gepusht. Kannst du dir den ziehen und Testen ob es nun passt?

```

20:04:22.679 | info | javascript.0 (10652) script.js.Skript_1: getState(id=valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR, timerId=undefined) => {"val":-2.78,"ack":true,"ts":1613415492931,"q":0,"from":"system.adapter.valloxmv.0","user":"system.user.admin","lc":1613415492931}
-- | -- | --
20:04:22.679 | info | javascript.0 (10652) script.js.Skript_1: number

```

**Comment by Feuer-sturm** [comment]
@hacki11 Hab soeben die Version von github installiert und jetzt kommen keine Warnungen mehr :-D
Danke für den schnellen Fix.

**Comment by hacki11** [comment]
Fixed in v1.1.2
