### ISSUE TITLE
External Change detection

### ISSUE THREAD

**Issue by williandalton** [hacki11/ioBroker.valloxmv#5]
Um den Adapter in einer Automatisierten Umgebung einzusetzen wäre es sinnvoll, wenn man den Zeitpunkt des letzten externen Eingriffs im Zugriff hätte. So kann man die Steuerung dahingehend anpassen, dass nach einem externen Eingriff nicht automatisiert "nachgeregelt" wird.

Beispiel:
Benutzer schreibt ein Skript, welches unter ioBroker die Lüftungsanlage in Abhängigkeit der Luftfeuchtigkeit aus- oder einschaltet. Damit soll z.B. erreicht werden, dass im Winter die Luftfeuchtigkeit nicht unter einen bestimmten Wert sinkt.

Sollte jetzt doch "außer der Reihe" über die normale Weboberfläche die Anlage trotz geringer Luftfeuchtigkeit eingeschaltete worden sein, soll dieser Zustand für die Zeitspanne X nicht verändert werden. Um X im steuernden Skript zu ermitteln, sollte der Zeitpunkt des letzten externen Eingriffs in einem State festgehalten werden.

**Comment by hacki11** [comment]
Ich bin noch recht neu in dem Thema, daher habe ich noch Fragen dazu.

Mit "externer Eingriff" meinst du eine Aktualisierung eines States, verursacht durch einen neuen Wert welcher vom Gerät selbst kommt. (Ursprünglich z.B. geändert durch die Weboberfläche).

Soweit ich das gesehen habe, gibt es für jeden State einen Zeitstempel der letzten Änderung.

Wenn nun ein User ein Script ausführt und den Zustand des Gerätes ändert, kann sich der User dann nicht den aktuellen Zeitsempel selbst irgendwo ablegen und bei erneuter Prüfung gegen den "last Changed" Zeitstempel des benötigten States gegenprüfen? Und somit feststellen, dass den Wert jemand anders geändert haben muss?

Evtl. verstehe ich den Use Case aber noch nicht ganz bzw. kenne mich mit dem Scripting von IOBroker noch nicht aus.

**Comment by williandalton** [comment]
Servus,

danke dass Du dir den Issue angesehen hast, aber ich glaube ich hatte da einen Denkfehler und das Feature wird in der Form doch nicht gebraucht.

Ich hatte ja schon mal erwähnt, dass ich meine Vallox bereits automatisiert steuere. 
Dabei stelle ich beim Auslesen vom aktuellen Status der Anlage fest, ob diese noch in dem Zustand läuft, den die Automatik zuvor vorgegeben hat.
Ist das nicht der Fall, gehe ich von einem externen Eingriff aus und stoppe die Automatik für einen längeren Zeitraum.

Im ioBroker muss diese Logik aber in die Automatisierungsschicht wandern.
Die Statusänderung könnte ja von der Weboberfläche der Vallox oder manuell über den ioBroker Adapter gekommen sein.

Ich denke ich portiere meine Automatisierungslogik bald nach JavaScript, kann ich bei Interesse dann auch gerne hier posten...

**Comment by hacki11** [comment]
Servus,

ja sehr gerne! Meine Lüftung läuft noch gar nicht, daher kann ich auch noch nichts steuern :D
Ich schlage vor, dass wenn du soweit bist, einfach ein neues Ticket mit deiner Anforderung erstellst und dann bekommen wir das schon hin.

**Comment by hliebscher** [comment]
Hi,
wollte kurz nachfragen ob Du noch "Methoden der Temperaturregelung" RW einfügen könntest.
Dann könnte man zeitgesteuert die Art der Temperaturregelung festlegen.
ABLUFT
ZULUFT
KRG (Kühlung)
wäre für den Sommer gut um die einströmende Luft per Wärmetauscher zu "kühlen"
mit freundlichen Grüßen
Heiko

**Comment by hacki11** [comment]
Hi, bitte ein neues Issue anlegen.
Kennst du zufällig die genauen Bezeichner bzw. Ein Screenshot der WebUi?

**Comment by williandalton** [comment]
Hi,

die Prozentwerte von Zu- und Abluft müssten in folgenden Konstanten zu finden sein:
VlxDevConstants.A_CYC_IN_SUPPLY_FAN
VlxDevConstants.A_CYC_IN_EXTRACT_FAN

![image](https://user-images.githubusercontent.com/45180031/56615765-13ded980-661c-11e9-8f91-6c57d7d25727.png)

Die habe ich aber noch nie verändert, wie möchtest du damit steuern? 
Kannst du genauer erklären, wie du die Luft über den Wärmetauscher kühlen möchtest? Nach meinem Verständnis sorgt der eher dafür, dass die Wärme im Winter im Haus bleibt. Es sei denn die ByPass Klappe ist auf, dann fällt die Funktion flach (was im Sommer ja auch Sinn macht :-)

Für meine Sommersteuerung sehe ich vor, dass die Anlage aus geht, wenn es draußen zu warm ist und im anderen Fall (also Nachts) stärker lüftet, also kühlt...

**Comment by williandalton** [comment]
Habe das Setting welches @hliebscher meinte gefunden, ist auch auf dem Screen der WebGUI zu sehen...

Zu konfigurierende Adresse:
Type of heating adjustment: CYC_SUPPLY_HEATING_ADJUST_MODE 20549

Mögliche Werte:
Value 0: Incoming air / C_CYC_HEATING_SUPPLY 
Value 1: Exhaust air / C_CYC_HEATING_EXTRACT 
Value 2: Cooling / C_CYC_HEATING_COOLING

**Comment by hliebscher** [comment]
Hi zusammen wollen wir das als neues Issue anlegen?
ich schreibe hier noch schnell die Antwort.

Verfahren zur Einstellung der Zulufttemperatur im Menü Methoden der Temperaturregelung. Die Optionen sind:

Bei Einstellung Zuluft—Zuluft wird das Nachheizregister verwendet, wenn die Temperatur der Luft, die aus dem Wärmetauscher kommt, niedriger als die eingestellte Temperatur der Zuluft ist. Der Wärmetauscher wird umgangen, wenn die Außentemperatur um mehr als zwei Grad von der eingestellten Temperatur der Zuluft abweicht und die Außentemperatur kälter als die Ablufttemperatur ist.

Bei Einstellung Abluft—Abluft wird die Zulufteinstellung abhängig von der Temperatur der Wohnungsabluft automatisch verändert (max. 10 °C).

Wird Einstellung KRG — KRG verwendet, funktioniert das Lüftungsgerät wie bei der Verwendung der Einstellung Abluft, es startet aber gegebenenfalls die Lüftung, bis das Profil geändert wird.

Im Fall KRG wird wenn die Zulufttemperatur 18 Grad sein soll und die Außentemperatur 21 ist die Luft(21) mit der abgesaugten Luft(18) gekühlt und die Anlage kann laufen da sonst im Sommer der CO Gehalt zu hoch wird.


Heiko

**Comment by williandalton** [comment]
Danke für den Input @hliebscher werde ich beim der Anlagensteuerung mit bedenken.

Ich glaube wir sind uns einig, dass eigentliche Issue durch ist, ich schließe daher dann mal...
