### ISSUE TITLE
Adapterversion 1.1.3 noch nicht im latest/beta Repository 

### ISSUE THREAD

**Issue by Feuer-sturm** [hacki11/ioBroker.valloxmv#54]
ValloxMV Version 1.1.2 ist aktuell im latest.

Mit js-controller 3.3.x wurde der ValloxMV Adapter entsprechend aktualisiert (v1.1.3).
Die Version 1.1.3 läuft stabil und kann damit mindestens ins latest / Beta Repository geschoben werden :-)

**Comment by hacki11** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/1321
