### ISSUE TITLE
Warning "Please add to "system.adapter.valloxmv" common.adminUI={"config":"materialize"}"

### ISSUE THREAD

**Issue by Feuer-sturm** [hacki11/ioBroker.valloxmv#61]
Admin 5.1.10
ValloxMV 1.1.2 to 1.1.3
Diskussion im Forum: https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/858

Während des Update von ValloxMV von 1.1.2 auf 1.1.3 kommt folgende Warnung in der Browser console:

![grafik](https://user-images.githubusercontent.com/25422320/125173420-8e757e80-e1bf-11eb-8e5a-6a3cef4ddcff.png)

**Comment by hacki11** [comment]
Muss nur das Flag gesetzt werden oder ist für Admin 5 ein kompletter Rewrite der UI umzusetzen?

**Comment by Feuer-sturm** [comment]
Ich denke dazu können @Apollon77 oder @Bluefox etwas sagen.

**Comment by Apollon77** [comment]
nein, und ist aktuell komplett opitional. am ende geht nur darik in io-package.json unter common ein 

```
adminUI: {"config":"materialize"}
```

einzufügen

**Comment by Zefau** [comment]
@Apollon77 greift die Änderung der `io-package.json` auch für bestehende Installationen? Ich hab den Code aufgenommen (https://github.com/Zefau/ioBroker.jarvis/blob/9cbc23079fc89ba07b374ea7183553d118776b12/io-package.json#L81) und die User erhalten den Fehler dennoch, siehe auch https://github.com/Zefau/ioBroker.jarvis/issues/1241#issuecomment-988334624

Ich hab aber auch noch `"materialize": true` (https://github.com/Zefau/ioBroker.jarvis/blob/master/io-package.json#L59) drin. Muss das jetzt raus?

**Comment by Apollon77** [comment]
Ich weiss jetzt nicht genau was admin checkt. Wenn admin nur nach dem "Materialize" flag checkt dann wäre das erklärbar und wäre meine erste annahme.Ist am Ende aber nur eine Info meldung ...

Wenn du "materialize=true" rausnimmstmustdu auch ne admin >=5.1 globalDep setzen!
