### ISSUE TITLE
Please release 1.2.0 and also add to stable very soon!!

### ISSUE THREAD

**Issue by Apollon77** [hacki11/ioBroker.valloxmv#70]
js-controller 3.3. will be released in some days

**Comment by hacki11** [comment]
Is it enough to just test it and see if there are warnings or errors or do i have to change dependency versions or ui components?

**Comment by Apollon77** [comment]
in my eyes "working without warnings" is the goal ... rest up to you  :-)

**Comment by Feuer-sturm** [comment]
@hacki11 I think this issue can be closed as well. On my system I don't have any issues with js-controller 3 or 4

**Comment by hacki11** [comment]
I think every version needs to be added to the stable repository. So I need to make a pull request there
