### ISSUE TITLE
Please fix Adapter issues!!

### ISSUE THREAD

**Issue by Apollon77** [hacki11/ioBroker.valloxmv#9]
[E130] No news found in io-package.json

[E301] Tests on Travis-ci.org are broken. Please fix.

**Comment by hacki11** [comment]
would be awesome if 
 Check contents of io-package.json
could be extended to check the required 'news' attribute

**Comment by Apollon77** [comment]
You mean in the "included tests"? Or which test?

**Comment by hacki11** [comment]
There is a testing lib for integration tests, which is checking required attributes:

https://github.com/ioBroker/testing/blob/396561c0ac1a63718e362c0f77148bb153b57df1/src/tests/packageFiles/index.ts#L96

**Comment by Apollon77** [comment]
aahh, could you please create an issue there to propose this addition ?! Thank you
